project:
  type: book
  output-dir: ../docs
  execute-dir: file

book:
  title: "Sustainable Digitalization - A primer"
  author: "Mario Angst"
  date: "02/05/2023"
  chapters:
    - index.qmd
    - sus.qmd
    - digi.qmd
    - susdigi.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: source

